import "./globals.css";
import Header from "@/components/Header";
import Footer from '@/components/Footer';
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils";
const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
  })



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        
      </head>
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable) + 'flex flex-col flex-1 min-h-[100vh] text-base'}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
